# Bot AimBooster

Vamos criar um Bot para jogar http://www.aimbooster.com/

## Pacotes necessários

In [2]:
!pip install pywin32
!pip install keyboard
!pip install pyautogui
!pip install opencv-python

## Imports

In [21]:
from pyautogui import *
import pyautogui
import time
import keyboard
import random
import win32api, win32con
import math

## Cor do centro

Para saber a cor do centro vamos executar o comando abaixo, e encontrar a cor do centro, e os limites da janela do jogo.

In [48]:
time.sleep(5)
pyautogui.displayMousePosition()

Press Ctrl-C to quit.


X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  58

X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  580 RGB: (255, 219, 19X: 1365 Y:  58

A cor do centro é (255, 219, 195)

In [11]:
red = 255
green = 219
blue = 195

## Função Click

Construindo a função que recebendo x, y clica nessa posição da tela.

In [29]:
def click(x,y):
    win32api.SetCursorPos((x,y))
    win32api.mouse_event(win32con.MOUSEEVENTF_LEFTDOWN,0,0)
    time.sleep(0.05) #This pauses the script for 0.1 seconds
    win32api.mouse_event(win32con.MOUSEEVENTF_LEFTUP,0,0)

## O Bot

Esse Bot simplesmente percorre todas as posições informadas pela janela "pyautogui.screenshot(region=(xi, yi, l, a))", e verifica se a cor red = 255, green = 219, blue = 195 é encontrar, ele também não permite que o próximo clique do mouse esteja a uma distância de 20 pixel.
Detalhe que pra parar o Bot basta precionar a tecla "q".

In [30]:
xi, yi = 1141, 379 
l, a = 1742-xi,  800-yi
xf, yf = 1742,  800

time.sleep(5)

while keyboard.is_pressed('q') == False:
    pic = pyautogui.screenshot(region=(xi, yi, l, a))
    width, height = pic.size
    x_click = 0
    y_click = 0
    
    for x in range(0, width, 5):
        for y in range(0, height, 5):
            r, g, b = pic.getpixel((x, y))
            if r == red and g == green and b == blue and math.sqrt((x-x_click)**2+(y-y_click)**2)>30:
                click(xi+x, yi+y)
                x_click = x
                y_click = y
            

KeyboardInterrupt: 